root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/bot ./cmd/bot"
  bin = "tmp/bot"
  delay = 200
  include_ext = ["go", "mod", "sum"]
  include_dir = ["cmd", "internal", "config"]
  exclude_dir = ["tmp", "vendor", ".git"]
  stop_on_error = false

[log]
  time = true